### ISSUE TITLE
Failed to execute the binary AiCSA

### ISSUE THREAD

**Issue by jesse-zhangh** [hktalent/AiCSA#5]
go
go version go1.21.5 linux/amd64
OS
Ubuntu 22.04

Execute record

`
$ sudo ./AiCSA 
2023/12/26 13:59:05 init config files is over .
2023/12/26 13:59:05 registered index: AiCSA
2023/12/26 13:59:05 using static-bleve-mapping resources from ./static/
2023/12/26 13:59:05 必须在上面初始化索引后 func:  0
2023/12/26 13:59:05 debug util1.GTls set ok
net.core.rmem_max = 2500000

sysctl: cannot stat /proc/sys/kern/ipc/maxsockbuf: No such file or directory
`

How can you fix this?

**Comment by hktalent** [comment]
https://github.com/GhostTroops/AiCSA/blob/2dcc936303f6009452517abb6b43857c8dfa8d96/pkg/utils.go#L44

Does not affect your correct operation
